Getter for complex species map is added
GooStats/GooStats pull request #28
Opened 2019-12-05 19:08 UTC by morningallergy

2019-12-05 19:10 UTC, neutralino-ai requested changes
The private should not be removed. Instead, a new getter should be added, or friend class can be added.

2019-12-06 14:20 UTC, morningallergy commented
I did not exactly remove private. I just added one line BEFORE private, but somehow it was treated as if I deleted private and then added it again (probably because of different offsets). Privacy of other attributes should have remained untouched.

2019-12-06 15:39 UTC, DingXuefeng commented
> I did not exactly remove private. I just added one line BEFORE private, but somehow it was treated as if I deleted private and then added it again (probably because of different offsets). Privacy of other attributes should have remained untouched.

You are right.

2019-12-06 15:39 UTC, neutralino-ai approved these changes

2019-12-06 15:41 UTC, merged